# -*- coding: utf-8 -*-
"""internship5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zez-Yx5JQWX8HdZdBQn-0xXItN2LMkZG
"""

import pandas as pd

# Load dataset
df = pd.read_excel("expanded_annotated_labeled_reddit_posts.xlsx")

# Define keyword lists
startup_keywords = [
    "start", "startup", "starting", "permits", "license", "licensing",
    "first steps", "new trailer", "new truck", "buying", "purchase",
    "planning", "business plan", "location", "commissary", "inspection",
    "costs", "budget", "loan"
]

operational_keywords = [
    "equipment", "generator", "power", "freezer", "fridge", "cold storage",
    "workflow", "staff", "hiring", "menu", "cooking", "holding", "prep",
    "profit", "cost control", "events", "parking", "daily operation",
    "sourcing", "ingredients", "POS", "maintenance"
]

def classify_post(text):
    text = str(text).lower()

    # Check startup keywords
    if any(word in text for word in startup_keywords):
        return "startup_help"

    # Check operational keywords
    if any(word in text for word in operational_keywords):
        return "operational_help"

    # Fallback: use sub_category if available
    if "start" in text or "permit" in text:
        return "startup_help"

    return "operational_help"  # default

# Apply classifier
df["ml_label"] = df["combined_text"].apply(classify_post)

# Save output
df.to_csv("reddit_with_ml_labels.csv", index=False)

df.head()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    df["combined_text"], df["ml_label"], test_size=0.2, random_state=42
)

# Build pipeline
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(stop_words="english")),
    ("clf", LogisticRegression(max_iter=200))
])

# Train model
pipeline.fit(X_train, y_train)

# Evaluate
accuracy = pipeline.score(X_test, y_test)
print("Accuracy:", accuracy)

"""Automatic Keyword Extraction Using TF‑IDF"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Combine text fields if needed
texts = df["combined_text"].fillna("")

# Create TF-IDF model
vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=2000,       # limit vocabulary
    ngram_range=(1, 2)       # unigrams + bigrams
)

tfidf_matrix = vectorizer.fit_transform(texts)

# Extract feature names
feature_names = vectorizer.get_feature_names_out()

# Function to get top keywords per post
def extract_keywords(row_index, top_n=10):
    row = tfidf_matrix[row_index].toarray().flatten()
    top_indices = row.argsort()[-top_n:][::-1]
    return [feature_names[i] for i in top_indices]

# Add keywords column
df["auto_keywords"] = [
    extract_keywords(i, top_n=8) for i in range(len(df))
]

# Save output
df.to_csv("reddit_with_auto_keywords.csv", index=False)

df[["id", "auto_keywords"]].head()

""" Use Arbitrary Numbers"""

# Extract unique subcategories
unique_subcats = sorted(df["sub_category"].dropna().unique())

# Create a mapping: subcategory → numeric ID
subcat_to_id = {subcat: idx for idx, subcat in enumerate(unique_subcats)}

print("Generated mapping:")
for k, v in subcat_to_id.items():
    print(f"{k}: {v}")

# Add new ML-friendly column
df["subcat_id"] = df["sub_category"].map(subcat_to_id)

# Save output
df.to_csv("reddit_with_subcat_ids.csv", index=False)

df[["sub_category", "subcat_id"]].head()

"""These numbers are Stable, Unique (no duplicates) and Meaningless (no mathematical relationship). Those numbers do not carry meaning by themselves.
They are simply labels, not rankings.

Lets try one hot encoding
"""

# One-hot encode the sub_category column
one_hot = pd.get_dummies(df["sub_category"], prefix="subcat")

# Add the one-hot columns to the dataframe
df = pd.concat([df, one_hot], axis=1)

# Save output
df.to_csv("reddit_with_onehot_subcategories.csv", index=False)

df.head()

# Target label (startup_help vs operational_help)
y = df["ml_label"]

# Features: text + subcategory
X = df[["combined_text", "sub_category"]]

# ---------------------------------------
# PREPROCESSING PIPELINE
# ---------------------------------------

# 1. TF-IDF for keyword extraction from text
text_transformer = TfidfVectorizer(
    stop_words="english",
    max_features=3000,
    ngram_range=(1, 2)
)

# 2. One-hot encoding for subcategories
subcat_transformer = OneHotEncoder(handle_unknown="ignore")

# 3. Combine both transformers
preprocessor = ColumnTransformer(
    transformers=[
        ("text", text_transformer, "combined_text"),
        ("subcat", subcat_transformer, ["sub_category"])
    ]
)

# ---------------------------------------
# FULL PIPELINE (Preprocessing + Classifier)
# ---------------------------------------
pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("clf", LogisticRegression(max_iter=300))
])

# ---------------------------------------
# TRAIN / TEST SPLIT
# ---------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ---------------------------------------
# TRAIN MODEL
# ---------------------------------------
pipeline.fit(X_train, y_train)

# ---------------------------------------
# EVALUATE
# ---------------------------------------
accuracy = pipeline.score(X_test, y_test)
print("Model Accuracy:", accuracy)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np




X = df[["combined_text", "sub_category"]]
y = df["ml_label"]


# PREPROCESSING PIPELINE
# ---------------------------------------
text_transformer = TfidfVectorizer(
    stop_words="english",
    max_features=3000,
    ngram_range=(1, 2)
)

subcat_transformer = OneHotEncoder(handle_unknown="ignore")

preprocessor = ColumnTransformer(
    transformers=[
        ("text", text_transformer, "combined_text"),
        ("subcat", subcat_transformer, ["sub_category"])
    ]
)

pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("clf", LogisticRegression(max_iter=300))
])


# TRAIN / TEST SPLIT
# ---------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# TRAIN MODEL
# ---------------------------------------
pipeline.fit(X_train, y_train)


# CONFUSION MATRIX
# ---------------------------------------
y_pred = pipeline.predict(X_test)

cm = confusion_matrix(y_test, y_pred, labels=["startup_help", "operational_help"])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Startup", "Operational"])

plt.figure(figsize=(6, 6))
disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix")
plt.show()

# Extract the trained classifier
clf = pipeline.named_steps["clf"]

# Extract feature names from both transformers
tfidf_features = pipeline.named_steps["preprocess"].named_transformers_["text"].get_feature_names_out()
subcat_features = pipeline.named_steps["preprocess"].named_transformers_["subcat"].get_feature_names_out()

all_features = np.concatenate([tfidf_features, subcat_features])

# Get coefficients for the "startup_help" class
coef = clf.coef_[0]

# Sort by absolute weight
top_n = 20
top_indices = np.argsort(np.abs(coef))[-top_n:]

plt.figure(figsize=(10, 8))
plt.barh(all_features[top_indices], coef[top_indices])
plt.title("Top Feature Importances (Logistic Regression)")
plt.xlabel("Coefficient Weight")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

